# Generated by Django 6.0.2 on 2026-03-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = []
