# Generated by Django 5.2.13 on 2026-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialauth',
            options={},
        ),
        migrations.AddField(
            model_name='socialauth',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialauth',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialauth',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
