# Generated by Django 5.2.12 on 2026-03-31 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(unique=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('relationships', 'Relationships'), ('self_care', 'Self Care'), ('general', 'General')], default='general', max_length=100)),
                ('reading_time', models.PositiveIntegerField(help_text='Estimated reading time in minutes')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
